cases = [ "Operation Riptide Case", "Snakebite Case", 
    "Operation Broken Fang Case", "Fracture Case", "Prisma 2 Case", "CS20 Case", 
    "Shattered Web Case", "Prisma Case", "Danger Zone Case", "Horizon Case", "Clutch Case", 
    "Spectrum 2 Case", "Operation Hydra Case", "Spectrum Case", "Glove Case", "Gamma 2 Case", 
    "Gamma Case", "Chroma 3 Case", "Operation Wildfire Case", "Revolver Case", "Shadow Case", 
    "Falchion Case", "Chroma 2 Case", "Chroma Case", "Operation Vanguard Weapon Case", 
    "eSports 2014 Summer Case", "Operation Breakout Weapon Case", "Huntsman Weapon Case", 
    "Operation Phoenix Weapon Case", "CS:GO Weapon Case 3", "Winter Offensive Weapon Case", 
    "eSports 2013 Winter Case", "CS:GO Weapon Case 2", "Operation Bravo Case", 
    "eSports 2013 Case", "CS:GO Weapon Case"
]  
# Not inclued because still in active drop pool
# "Gallery Case", "Kilowatt Case", "Anubis Collection Package", "Revolution Case", "Recoil Case", "Dreams & Nightmares Case"
major_sticker_capsules_list = [
    "Shanghai 2024 Contenders Sticker Capsule",
    "Shanghai 2024 Challengers Sticker Capsule",
    "Shanghai 2024 Legends Sticker Capsule",
    "Copenhagen 2024 Contenders Sticker Capsule",
    "Copenhagen 2024 Challengers Sticker Capsule",
    "Copenhagen 2024 Legends Sticker Capsule",
    "Paris 2023 Contenders Sticker Capsule",
    "Paris 2023 Challengers Sticker Capsule",
    "Paris 2023 Legends Sticker Capsule",
    "Rio 2022 Contenders Sticker Capsule",
    "Rio 2022 Challengers Sticker Capsule",
    "Rio 2022 Legends Sticker Capsule",
    "Antwerp 2022 Contenders Sticker Capsule",
    "Antwerp 2022 Challengers Sticker Capsule",
    "Antwerp 2022 Legends Sticker Capsule",
    "Stockholm 2021 Contenders Sticker Capsule",
    "Stockholm 2021 Challengers Sticker Capsule",
    "Stockholm 2021 Legends Sticker Capsule",
    "Berlin 2019 Minor Challengers (Holo/Foil)",
    "Berlin 2019 Returning Challengers (Holo/Foil)",
    "Berlin 2019 Legends (Holo/Foil)",
    "Katowice 2019 Minor Challengers (Holo/Foil)",
    "Katowice 2019 Returning Challengers (Holo/Foil)",
    "Katowice 2019 Legends (Holo/Foil)",
    "London 2018 Minor Challengers (Holo/Foil)",
    "London 2018 Returning Challengers (Holo/Foil)",
    "London 2018 Legends (Holo/Foil)",
    "Boston 2018 Attending Legends (Holo/Foil)",
    "Boston 2018 Minor Challengers with Flash Gaming (Holo/Foil)",
    "Boston 2018 Minor Challengers (Holo/Foil)",
    "Boston 2018 Returning Challengers (Holo/Foil)",
    "Boston 2018 Legends (Holo/Foil)",
    "Krakow 2017 Challengers (Holo/Foil)",
    "Krakow 2017 Legends (Holo/Foil)",
    "Atlanta 2017 Challengers (Holo/Foil)",
    "Atlanta 2017 Legends (Holo/Foil)",
    "Cologne 2016 Challengers (Holo/Foil)",
    "Cologne 2016 Legends (Holo/Foil)",
    "MLG Columbus 2016 Challengers (Holo/Foil)",
    "MLG Columbus 2016 Legends (Holo/Foil)",
    "DreamHack Cluj-Napoca 2015 Challengers (Foil)",
    "DreamHack Cluj-Napoca 2015 Legends (Foil)",
    "ESL One Cologne 2015 Challengers (Foil)",
    "ESL One Cologne 2015 Legends (Foil)",
    "ESL One Katowice 2015 Challengers (Holo/Foil)",
    "ESL One Katowice 2015 Legends (Holo/Foil)",
    "DreamHack 2014 Legends (Holo/Foil)",
    "ESL One Cologne 2014 Challengers",
    "ESL One Cologne 2014 Legends"
]

ancien_collection_list = ancient_collection_skins = [
    "M4A1-S | Welcome to the Jungle",
    "AK-47 | Panthera onca",
    "P90 | Run and Hide",
    "XM1014 | Ancient Lore",
    "MAC-10 | Gold Brick",
    "USP-S | Ancient Visions",
    "Galil AR | Dusk Ruins",
    "AUG | Carved Jade",
    "Tec-9 | Blast From the Past",
    "FAMAS | Dark Water",
    "MP7 | Tall Grass",
    "P2000 | Panther Camo",
    "CZ75-Auto | Silver",
    "G3SG1 | Ancient Ritual",
    "SSG 08 | Jungle Dashed",
    "P90 | Ancient Earth",
    "R8 Revolver | Night",
    "SG 553 | Lush Ruins",
    "Nova | Army Sheen"
]